version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: bidding-postgres
    restart: always
    environment:
      POSTGRES_DB: bidding_db
      POSTGRES_USER: bidding_user
      POSTGRES_PASSWORD: bidding_pass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: bidding-backend
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bidding_db
      SPRING_DATASOURCE_USERNAME: bidding_user
      SPRING_DATASOURCE_PASSWORD: bidding_pass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"

volumes:
  postgres_data: